import {Server} from 'miragejs';

export default () => {
  new Server({
    routes() {
      this.namespace = 'api';

      this.get('/users', () => {
        return {
          users: [
            {
              login: 'Artemas-Muzanenhamo',
              id: 29547780,
              node_id: 'MDQ6VXNlcjI5NTQ3Nzgw',
              avatar_url: 'https://avatars0.githubusercontent.com/u/29547780?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/Artemas-Muzanenhamo',
              html_url: 'https://github.com/Artemas-Muzanenhamo',
              followers_url: 'https://api.github.com/users/Artemas-Muzanenhamo/followers',
              following_url: 'https://api.github.com/users/Artemas-Muzanenhamo/following{/other_user}',
              gists_url: 'https://api.github.com/users/Artemas-Muzanenhamo/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/Artemas-Muzanenhamo/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/Artemas-Muzanenhamo/subscriptions',
              organizations_url: 'https://api.github.com/users/Artemas-Muzanenhamo/orgs',
              repos_url: 'https://api.github.com/users/Artemas-Muzanenhamo/repos',
              events_url: 'https://api.github.com/users/Artemas-Muzanenhamo/events{/privacy}',
              received_events_url: 'https://api.github.com/users/Artemas-Muzanenhamo/received_events',
              type: 'User',
              site_admin: false,
              name: 'Artemas Muzanenhamo',
              company: 'Pictopage',
              blog: 'https://www.linkedin.com/in/artemasmuzanenhamo/',
              location: 'London',
              email: null,
              hireable: null,
              bio: 'Software Engineer',
              twitter_username: null,
              public_repos: 75,
              public_gists: 2,
              followers: 15,
              following: 18,
              created_at: '2017-06-19T15:44:50Z',
              updated_at: '2020-08-15T21:25:50Z'
            },
            {
              login: 'Artemas-Muzanenhamo',
              id: 29547780,
              node_id: 'MDQ6VXNlcjI5NTQ3Nzgw',
              avatar_url: 'https://avatars0.githubusercontent.com/u/29547780?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/Artemas-Muzanenhamo',
              html_url: 'https://github.com/Artemas-Muzanenhamo',
              followers_url: 'https://api.github.com/users/Artemas-Muzanenhamo/followers',
              following_url: 'https://api.github.com/users/Artemas-Muzanenhamo/following{/other_user}',
              gists_url: 'https://api.github.com/users/Artemas-Muzanenhamo/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/Artemas-Muzanenhamo/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/Artemas-Muzanenhamo/subscriptions',
              organizations_url: 'https://api.github.com/users/Artemas-Muzanenhamo/orgs',
              repos_url: 'https://api.github.com/users/Artemas-Muzanenhamo/repos',
              events_url: 'https://api.github.com/users/Artemas-Muzanenhamo/events{/privacy}',
              received_events_url: 'https://api.github.com/users/Artemas-Muzanenhamo/received_events',
              type: 'User',
              site_admin: false,
              name: 'Artemas Muzanenhamo',
              company: 'Pictopage',
              blog: 'https://www.linkedin.com/in/artemasmuzanenhamo/',
              location: 'London',
              email: null,
              hireable: null,
              bio: 'Software Engineer',
              twitter_username: null,
              public_repos: 75,
              public_gists: 2,
              followers: 15,
              following: 18,
              created_at: '2017-06-19T15:44:50Z',
              updated_at: '2020-08-15T21:25:50Z'
            },
            {
              login: 'Artemas-Muzanenhamo',
              id: 29547780,
              node_id: 'MDQ6VXNlcjI5NTQ3Nzgw',
              avatar_url: 'https://avatars0.githubusercontent.com/u/29547780?v=4',
              gravatar_id: '',
              url: 'https://api.github.com/users/Artemas-Muzanenhamo',
              html_url: 'https://github.com/Artemas-Muzanenhamo',
              followers_url: 'https://api.github.com/users/Artemas-Muzanenhamo/followers',
              following_url: 'https://api.github.com/users/Artemas-Muzanenhamo/following{/other_user}',
              gists_url: 'https://api.github.com/users/Artemas-Muzanenhamo/gists{/gist_id}',
              starred_url: 'https://api.github.com/users/Artemas-Muzanenhamo/starred{/owner}{/repo}',
              subscriptions_url: 'https://api.github.com/users/Artemas-Muzanenhamo/subscriptions',
              organizations_url: 'https://api.github.com/users/Artemas-Muzanenhamo/orgs',
              repos_url: 'https://api.github.com/users/Artemas-Muzanenhamo/repos',
              events_url: 'https://api.github.com/users/Artemas-Muzanenhamo/events{/privacy}',
              received_events_url: 'https://api.github.com/users/Artemas-Muzanenhamo/received_events',
              type: 'User',
              site_admin: false,
              name: 'Artemas Muzanenhamo',
              company: 'Pictopage',
              blog: 'https://www.linkedin.com/in/artemasmuzanenhamo/',
              location: 'London',
              email: null,
              hireable: null,
              bio: 'Software Engineer',
              twitter_username: null,
              public_repos: 75,
              public_gists: 2,
              followers: 15,
              following: 18,
              created_at: '2017-06-19T15:44:50Z',
              updated_at: '2020-08-15T21:25:50Z'
            }
          ],
        };
      });

      this.get('/users/artemas-muzanenhamo', () => {
        return {
          login: 'Artemas-Muzanenhamo',
          id: 29547780,
          node_id: 'MDQ6VXNlcjI5NTQ3Nzgw',
          avatar_url: 'https://avatars0.githubusercontent.com/u/29547780?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/Artemas-Muzanenhamo',
          html_url: 'https://github.com/Artemas-Muzanenhamo',
          followers_url: 'https://api.github.com/users/Artemas-Muzanenhamo/followers',
          following_url: 'https://api.github.com/users/Artemas-Muzanenhamo/following{/other_user}',
          gists_url: 'https://api.github.com/users/Artemas-Muzanenhamo/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/Artemas-Muzanenhamo/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/Artemas-Muzanenhamo/subscriptions',
          organizations_url: 'https://api.github.com/users/Artemas-Muzanenhamo/orgs',
          repos_url: 'https://api.github.com/users/Artemas-Muzanenhamo/repos',
          events_url: 'https://api.github.com/users/Artemas-Muzanenhamo/events{/privacy}',
          received_events_url: 'https://api.github.com/users/Artemas-Muzanenhamo/received_events',
          type: 'User',
          site_admin: false,
          name: 'Artemas Muzanenhamo',
          company: 'Pictopage',
          blog: 'https://www.linkedin.com/in/artemasmuzanenhamo/',
          location: 'London',
          email: null,
          hireable: null,
          bio: 'Software Engineer',
          twitter_username: null,
          public_repos: 75,
          public_gists: 2,
          followers: 15,
          following: 18,
          created_at: '2017-06-19T15:44:50Z',
          updated_at: '2020-08-15T21:25:50Z'
        };
      });
    },
  });
};
